name: 'Bike Club contact forms'
description: 'Provides personal contact form and forms for website feedback, membership, and rides.'
type: 'Contact form'
install:
  - contact
  - views
# Contrib
  - contact_storage
config:
  import:
    contact:
      - contact.form.personal
    # Do not include 'system.action.contact_message_delete_action'. Its reformatted and rejected upon reinstall.
    # Reformatted version is in recipe config folder.
    contact_storage:
      - 'contact_storage.settings'
      - 'views.view.contact_messages'
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'access site-wide contact form'
        - 'access user contact forms'
    user.role.authenticated:
      grantPermissions:
        - 'access site-wide contact form'
        - 'access user contact forms'
    user.role.site_admin:
      grantPermission: 'administer contact forms'
